/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove MulleThread`
// (Use 9053A17B-A774-4810-8090-807670393DBC instead of MulleThread, if there are duplicate entries)
//
// You can tweak the following #import with these commands:
//    remove #import      : `mulle-sde dependency mark MulleThread no-header`
//    rename              : `mulle-sde dependency|library set MulleThread include whatever.h`
//    reorder             : `mulle-sde dependency move MulleThread <up|down>`
//    toggle #import      : `mulle-sde dependency mark MulleThread [no-]import`
//    toggle public       : `mulle-sde dependency mark MulleThread [no-]public`
//    toggle optional     : `mulle-sde dependency mark MulleThread [no-]require`
//    remove for platform : `mulle-sde dependency mark MulleThread no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleThread/MulleThread.h>   // MulleThread

#ifdef __has_include
# if __has_include( "_MulleInvocationQueue-include.h")
#  include "_MulleInvocationQueue-include.h"
# endif
#endif

