      { @selector( MulleObjCLoader), @selector( MulleFoundationBase) },      // 47a9beb6;MulleObjCLoader;efab19ea;MulleFoundationBase
      { @selector( MulleObjCLoader), @selector( MulleThread) },      // 47a9beb6;MulleObjCLoader;c7c34b28;MulleThread
      { @selector( MulleInvocationQueue), MULLE_OBJC_NO_CATEGORYID },      // 9a5137b3;MulleInvocationQueue;;
      { @selector( MulleSingleTargetInvocationQueue), MULLE_OBJC_NO_CATEGORYID },      // 62f0858e;MulleSingleTargetInvocationQueue;;
      { @selector( NSInvocation), @selector( MulleReturnStatus) },      // c089c043;NSInvocation;bd6f8a28;MulleReturnStatus
      { @selector( NSInvocation), @selector( UTF8String) },      // c089c043;NSInvocation;0a62c4be;UTF8String
